
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // DATABASE_URL jest opcjonalny dla prisma generate (nie jest potrzebny do generowania klienta)
    url: env("DATABASE_URL", { optional: true }) || "postgresql://placeholder",
  },
  seed: {
    command: "tsx prisma/seed.ts",
  },
});
