
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // DATABASE_URL jest opcjonalny dla prisma generate (nie jest potrzebny do generowania klienta)
    // Używamy process.env bezpośrednio, aby uniknąć błędu podczas postinstall
    url: process.env.DATABASE_URL || "postgresql://placeholder",
  },
  seed: {
    command: "tsx prisma/seed.ts",
  },
});
